services:
  - name: beacon-node
    image: gcr.io/whiteblock/beacon:buttchug
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
    script:
      inline: /app/beacon-chain/image.binary --datadir=/data --interop-num-validators=1024 --no-discovery --interop-eth1data-votes --enable-attestation-cache --enable-ssz-cache --enable-skip-slots-cache
  - name: explorer
    image: gobitfly/eth2-beaconchain-explorer
    input-files:
    - source-path: ./config.yaml
      destination-path: /var/explorer/config.yaml
    args:
      - '-config=/var/explorer/config.yaml'
  - name: postgres
    image: postgres
    input-files:
    - source-path: ./psql.sh
      destination-path: /docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: genesis
      POSTGRES_USER: genesis
      POSTGRES_PASSWORD: genesis
  - name: prometheus
    image: prom/prometheus
    input-files:
    - source-path: ./prometheus.yaml
      destination-path: /etc/prometheus/prometheus.yml

  - name: validator
    image: gcr.io/whiteblock/validator:buttchug
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
    script:
      inline: /app/validator/image.binary --keymanager=interop --keymanageropts='{"keys":1024}' --beacon-rpc-provider=$_one_of(beacon-node,network-1):4000
tests:
  - name: prysm-partition
    description: "run a prysm testnet and implement a network partition"
    wait-for: 2m
    system:
      - type: beacon-node
        count: 2
        resources:
          networks:
            - name: network-1
      - type: postgres
        resources:
          networks:
            - name: network-1
      - type: prometheus
        port-mappings:
          - 9090:9090
        resources:
          networks:
            - name: network-1
    phases:
      - name: start-printer
        duration: 2m
        system:
        - type: validator
          count: 20
          resources:
            networks:
            - name: network-1
      - name: explorer
        duration: infinite
        system:
        - type: explorer
          resources:
            networks:
            - name: network-1
