services:
  - name: bootnode
    image: gcr.io/whiteblock/bootnode:buttchug
    resources:
      cpus: 2
      memory: 4 GB
    script:
      inline: /app/tools/bootnode/image.binary --external-ip 0.0.0.0 --private 3a26b674e9c0c849c43881bf5ac4a8f34b882ac94742869d668bff52825ac1c2
  - name: beacon-node
    image: gcr.io/whiteblock/beacon:buttchug
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
    script:
      inline: /app/beacon-chain/image.binary --archive --datadir=/data --interop-num-validators=1024 --no-discovery --interop-eth1data-votes --enable-attestation-cache --enable-ssz-cache --enable-skip-slots-cache --bootstrap-node /dns4/bootnode-service0/tcp/4500/p2p/16Uiu2HAmFqaBuKYvjubCx8QoUEr1gxR4hWU9MxFMUmz2MNqzMD9Q/5w==
  - name: explorer
    image: gobitfly/eth2-beaconchain-explorer
    script:
      inline: /app/explorer -config=/var/explorer/config.yaml
    input-files:
    - source-path: ./config.yaml
      destination-path: /var/explorer/config.yaml
  - name: postgres
    image: postgres
    input-files:
    - source-path: ./psql.sh
      destination-path: /docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: genesis
      POSTGRES_USER: genesis
      POSTGRES_PASSWORD: genesis
  - name: prometheus
    image: prom/prometheus
    input-files:
    - source-path: ./prometheus.yaml
      destination-path: /etc/prometheus/prometheus.yml
    script:
      # soo hacky thx n8wb for this
      inline: sed -i "s/HOSTNAME/$(wget -qO- ifconfig.co)/" /etc/prometheus/prometheus.yml && /bin/prometheus --config.file /etc/prometheus/prometheus.yml
  - name: validator
    image: gcr.io/whiteblock/validator:buttchug
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
    script:
      inline: /app/validator/image.binary --keymanager=interop --keymanageropts='{"keys":1024}' --beacon-rpc-provider=$_one_of(beacon-node,network-1):4000
tests:
  - name: prysm-partition
    description: "run a prysm testnet and implement a network partition"
    wait-for: 30s
    system:
    - type: bootnode
      resources:
        networks:
          - name: network-1
    phases:
      - name: beacons
        duration: 90s
        system:
        - type: beacon-node
          count: 2
          resources:
            networks:
              - name: network-1
        - type: postgres
          resources:
            networks:
              - name: network-1
        - type: prometheus
          port-mappings:
            - 9090:9090
          resources:
            networks:
              - name: network-1
      - name: start-validator
        duration: 1m
        system:
        - type: validator
          count: 20
          resources:
            networks:
            - name: network-1
      - name: explorer
        duration: infinite
        system:
        - type: explorer
          port-mappings:
          - "80:3333"
          resources:
            networks:
            - name: network-1
