services:
  - name: beacon-node
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest-debug
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
    script:
      inline: | 
        /app/beacon-chain/image.binary 
        --datadir=/data 
        --interop-num-validators=1024 
        --no-discovery 
        --interop-eth1data-votes 
        --enable-attestation-cache
        --enable-ssz-cache
        --enable-skip-slots-cache 
sidecars:
  - name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    sidecar-to: [ "beacon-node" ]
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
    script:
      inline: |
        sleep 120 && 
        /app/validator/image.binary 
        --keymanager=interop
        --keymanageropts='{"keys":1024}'
        --beacon-rpc-provider=$SERVICE:4000

tests:
  - name: prysm-partition
    description: "run a prysm testnet and implement a network partition"
    wait-for: infinite 
    system:
      - type: beacon-node
        count: 10
        resources:
           networks:
             - name: network-1
