services:
  - name: beacon-node
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest-debug
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
  - name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:latest-debug
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
  - name: beacon-node2
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest-debug
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
  - name: validator2
    image: gcr.io/prysmaticlabs/prysm/validator:latest-debug
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
tests:
  - name: simple-prysm-exercise
    description: "run a prysm testnet and validate some blocks"
    wait-for: 1 m #wait for this amount of time before starting validators
    system:
      - type: beacon-node
        count: 1
        resources:
           networks:
             - name: common-network
      - type: beacon-node2
        count: 1
        resources:
           networks:
             - name: common-network
    phases:
      - name: validators
        system:
        - type: validator
          count: 1
          resources:
             networks:
               - name: common-network
        - type: validator2
          count: 1
          resources:
             networks:
               - name: common-network
      - name: partition
        description: partition the nodes
        system:
          - type: beacon-node
            resources:
              networks:
                - name: common-network
          - type: beacon-node2
            resources:
              networks:
                - name: common-network2
          - type: validator
            resources:
              networks:
                - name: common-network
          - type: validator2
            resources:
              networks:
                - name: common-network2
        duration: 5 m
      - name: merge
        system:
          - type: beacon-node
            resources:
              networks:
                - name: common-network
          - type: beacon-node2
            resources:
              networks:
                - name: common-network
          - type: validator
            resources:
              networks:
                - name: common-network
          - type: validator2
            resources:
              networks:
                - name: common-network
        duration: 5 m
